### ISSUE TITLE
Mobile-Friendly?

### ISSUE THREAD

**Issue by marioseixas** [shinemoon/shinemoon.github.io#1]
Hello

I'm using your template in my blog (http://mario.blog.br/) and I would like it to be mobile-friendly:

https://www.google.com/webmasters/tools/mobile-friendly/

Is that possible?

Thanks, awesome work you are doing here

**Comment by shinemoon** [comment]
Hi Mario,

Thanks for your comment and selection of my template (though a bit suprised honestly, since I made this template purely for myself's usage..) , and sorry that till now I have no more time to put into the mobilizing for that, as I have no such need personally... but who knows, maybe one day I come back for that topic?

Enjoying Jekyl..
